### ISSUE TITLE
[Request] Option to replace step with answer in tool-tip

### ISSUE THREAD

**Issue by Infinitay** [Zoinkwiz/clue-details#15]
Would it be possible to show the answer to the clue rather than the step/contents/cords of the clue on its tool-tip? Personally, I find that easier to track what a clue (I'm juggling) is rather than the actual step or clue content. I remember seeing in the RL Discord they are working on cross-plugin communication. If it's supported already, maybe you could leverage the answers from that plugin?

Thanks

**Comment by Zoinkwiz** [comment]
I've made it so you can now right-click steps to edit their text, as well as right-click import on the text 'Clue Details' at the top of the sidebar, so you can import a JSON file of the following form:

```
{
"CLUE_ID" : "TEXT TO USE"
}
```

This should mean any possible sorts of text to be displayed should be possible, and easily shared amongst anyone wanting to customise the text.
