### ISSUE TITLE
missing clue ID info

### ISSUE THREAD

**Issue by Felanbird** [Zoinkwiz/clue-details#4]
writing down info as I run into it with clue steps yet to be handled

<details>
<summary>CLUE_SCROLL_MEDIUM_23138</summary>

![image](https://github.com/user-attachments/assets/5f32bd2c-3f35-42c3-84c1-c74bce2b58c2)

</details>

<details>
<summary>CLUE_SCROLL_MEDIUM_23140</summary>

![image](https://github.com/user-attachments/assets/1264a895-818f-4681-b62a-042152ccbd38)

</details>

**Comment by Infinitay** [comment]
CLUE_SCROLL_HARD_23176 also is missing

**Comment by Felanbird** [comment]
> CLUE_SCROLL_HARD_23176 also is missing

What step was it?

**Comment by Infinitay** [comment]
> CLUE_SCROLL_HARD_23176

Shit... I thought each step had a unique ID after finding out that each clue was assigned a specific ID. Unfortunately I didn't take a screenshot or note of the step. Lately I've been clue hunting so I hope I can come across it again to share the step.

**Comment by Felanbird** [comment]
> Shit... I thought each step had a unique ID after finding out that each clue was assigned a specific ID. Unfortunately I didn't take a screenshot or note of the step. Lately I've been clue hunting so I hope I can come across it again to share the step.

Easy/Medium/Hard/Elite clues do all have unique IDs, but RuneLite handles steps unrelated to their ID, and they don't save any info for Cecilia steps as they are consistently written the same way.
